#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-doc doDoxygen' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

wmakeCheckPwd "$WM_PROJECT_DIR" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

# wmake is required for subsequent targets
if ! isMinGW; then

  ( cd wmake/src && make )

elif ! onWin; then

  if [ -d "wmake/bin/$WM_ARCH$WM_COMPILER" ]; then
    filecount=`ls -1A "wmake/bin/$WM_ARCH$WM_COMPILER" | wc -l`
  fi

  if [ "$filecount" = "0" -o ! -d "wmake/platforms/$WM_ARCH$WM_COMPILER" ]; then
    ( cd wmake/src && make WMAKE_BIN="${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}_win" EXE_EXTENSION=".exe" ADDITIONAL_CFLAGS="_WIN_HACK_" )
    ( cd wmake/src && make cc="gcc" CC="g++" )
  fi
  filecount=`ls -1A "wmake/platforms/$WM_ARCH$WM_COMPILER" | wc -l`

  #use the wmake compiled for linux usage, if not built with system's gcc
  if [ "$filecount" = "0" -o ! -d "wmake/platforms/$WM_ARCH$WM_COMPILER" ]; then
    echo "Aborting Allwmake, because a working wmake wasn't found nor built."
    exit 1
  fi
  unset filecount

else

  (
    cd wmake/src && \
    make && \
    mv ${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}/wmkdepend.exe \
       ${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}/wmkdep.exe
  )

fi

# build ThirdParty sources
if [ -d "$WM_THIRD_PARTY_DIR" ]
then
    $WM_THIRD_PARTY_DIR/Allwmake
else
    echo "no ThirdParty sources found - skipping"
fi

# build OpenFOAM libraries and applications
src/Allwmake $*
applications/Allwmake $*

if [ $doDoxygen -gt 0 ]
then
    doc/Allwmake $*
fi

# ----------------------------------------------------------------- end-of-file
