#!/bin/sh
#------------------------------------------------------------------------------
# License
#    Copyright (C) 2013 blueCAPE Lda
#
#    This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#    For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#    This file is a derivative work of OpenFOAM.
#
#    OpenFOAM is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     multiBuilderScotch
#
# Description
#     Help script for building multiple WM_OPTIONS builds sequentially,
#   specifically for only building and apcking all of the Scotch dummysizes.exe
#   binaries. 
#   
#
#------------------------------------------------------------------------------

#---------- Functions -------------
usage() {
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/}

This will run as a scripted multi-builder of WM_OPTIONS based on each
prefs-*.sh version given or additional variables. NOTE: you cannot have the
OpenFOAM environment activated prior to executing this script!!

USAGE
    exit 1
}

#argument: bashrc options
buildIt()
{
  (
    . etc/bashrc $*

    timeStamp=$(date +%Y-%m-%d_%H-%M)
    logFile="$BUILD_LOG_FOLDER/Allwmake_${WM_OPTIONS}_${timeStamp}.log"

    echo "Building $WM_OPTIONS with $WM_MPLIB ..."
    cd $WM_THIRD_PARTY_DIR

    #Make sure the stubs are done for the respective library
    ./AllwmakeMinGWMPI > $logFile 2>&1 && \
    time ./AllwmakeMinGWScotch cross4win >> $logFile 2>&1 || \
    echo "There seems to have been some problems with this build. Check the log: $logFile"
  )
}

#argument: bashrc options
packageThem()
{
  (
    . etc/bashrc $*

    timeStamp=$(date +%Y-%m-%d_%H-%M)
    logFile="$BUILD_LOG_FOLDER/Allwmake_${WM_OPTIONS}_${timeStamp}.log"

    echo "Packaging Scotch dummysizes.exe for $WM_OPTIONS ..."
    cd $WM_THIRD_PARTY_DIR
    ./packageScotchDummySizes || \
    echo "There seems to have been some problems with this build. Check the log: $logFile"
  )
}

#---------- script ----------------

if [ "x$1" = "x--sourceonly" ]
then
    : #do nothing...
elif [ "x$1" = "x--help" -o $# -gt 0 -o "x$WM_PROJECT_DIR" != "x" ]
then
    usage
fi

#Source buildLogs helper stuff
. ./bin/tools/BuildLogFunctions

if [ "x$1" != "x--sourceonly" ]
then

  #build with Open-MPI ------------------------------------------------
  # buildIt prefs-mingw32.sh

  buildIt prefs-mingw-w32.sh
  buildIt prefs-mingw-w64.sh

  #build with MPICH2 ------------------------------------------------
  # buildIt prefs-mingw32.sh WM_MPLIB=MPICH

  # buildIt prefs-mingw-w32.sh WM_MPLIB=MPICH
  # buildIt prefs-mingw-w64.sh WM_MPLIB=MPICH

  #build with MSMPI 2008 ------------------------------------------------
  # buildIt prefs-mingw32.sh WM_MPLIB=MSMPI2008

  buildIt prefs-mingw-w32.sh WM_MPLIB=MSMPI2008
  buildIt prefs-mingw-w64.sh WM_MPLIB=MSMPI2008

  #build with MSMPI 2012 ------------------------------------------------
  # buildIt prefs-mingw32.sh WM_MPLIB=MSMPI2012

  buildIt prefs-mingw-w32.sh WM_MPLIB=MSMPI2012
  buildIt prefs-mingw-w64.sh WM_MPLIB=MSMPI2012

  #package the dummysizes.exe et al
  packageThem prefs-mingw-w32.sh
  packageThem prefs-mingw-w64.sh

fi
