#!/bin/sh
#------------------------------------------------------------------------------
# License
#     Copyright (C) 2014 blueCAPE Lda
#
#     This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     wmake/smartSchedulerCompiler
#
# Description
#     Part of the smart scheduling scripts created for blueCFD-Core, to rely on
#     shell scripting to handle multicore compiling.
#
#------------------------------------------------------------------------------

originalCode="$@"
objectFile=""

# parse options
while [ "$#" -gt 0 ]
do
   case "$1" in
   -o)
      objectFile=$2
      break
      ;;
   *)
      shift
      ;;
   esac
done

if [ -n "${objectFile}" ]; then
  echo "${originalCode}" > "${objectFile}"
  echo ": SCHEDULED"
else
  echo "No valid object file name was found."
  exit 1
fi

#------------------------------------------------------------------------------
